on:
  workflow_dispatch:
jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Modifiy the specific files using scripts
        run: |
          rm -f  ./docs/index.html
          touch ./docs/index.html
          cat  ./docs/template/head.html >> ./docs/index.html
          echo "25" >> ./docs/index.html
          cat ./docs/template/tail.html >> ./docs/index.html 
    
    
    
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GH_USERENAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
    
          git add -A
          git commit -m "commit message"
          git push
