on:
  workflow_dispatch:
jobs:
  job1:
    name: Create and fill index.html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Delete  index.html
        run: |
            rm -f  ./docs/index.html

      - name: Create index.html
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: 'docs'
          isAbsolutePath: false
          file: 'index.html'

      - name: Add head template to index.html
        run: |
          cat  ./docs/template/head.html >> ./docs/index.html
    
  job2:
    name: Fetch data
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Get random number
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.random.org/json-rpc/4/invoke'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"jsonrpc": "2.0", "method": "generateIntegers", "id": "1", "params": {"apiKey": "${{ secrets.RAND_APIKEY }}", "n": 1, "min": 0, "max": 1e9}}'

      - name: Show Response
        run: |
          echo  ${{ fromJson(steps.myRequest.outputs.response).result.random.data }}

  job3:
    name: Fill and push index.html
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Add tail template to index.html
        run: |
          cat ./docs/template/tail.html >> ./docs/index.html 
    
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GH_USERENAME }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
    
          git add -A
          git commit -m "commit message"
          git push
